### ISSUE TITLE
Missed file in dist directory

### ISSUE THREAD

**Issue by VitoCrl** [tripolskypetr/ecg-line-webcomponent#1]
You forgot to put in your /dist directory the file imported in the index named "dist/ecg-webcomponent.js", 
It doesn't make the program work

**Comment by tripolskypetr** [comment]
Try "npm install & npm run build" :-)

чт, 24 сент. 2020 г. в 15:38, zOmegaaa <notifications@github.com>:

**Comment by tripolskypetr** [comment]
I have uploaded the compiled version of the web component to the dist
folder, try to pull last changes to your local git repository

чт, 24 сент. 2020 г. в 19:07, Трипольский Пётр <tripolskypetr@gmail.com>:
