### ISSUE TITLE
Not very clear

### ISSUE THREAD

**Issue by VitoCrl** [tripolskypetr/ecg-line-webcomponent#3]
Honestly man, the script is very nice, but I don't really understand how I can integrate your webcomponents with for example the health data server, I have in my index.html file (heart Data server directory) where my heart rate is written every second, how I can integrate your bang function for display the ecg monitor ?

**Comment by tripolskypetr** [comment]
Well, actually, quite simple. Call `bang()` on every incoming beat of heart. The provided callback is designed for a closure, inside which there can be an recursive interval with timeout and an ajax([fetch](https://developer.mozilla.org/en/docs/Web/API/Fetch_API)) request

> Also, if you need an React interop, use the [demo on JSFiddle](https://jsfiddle.net/tripolskypetr/sbfq8he2/10/)

```
<!--script src="dist/ecg-webcomponent.js"></script-->

<div id="mount-point"></div>

<script>
  (function () {

    const {
      useRef,
      useEffect,
    } = React;

    const {
      createElement: h,
    } = React;

    const App = () => {

      const ref = useRef(null);

      useEffect(() => {
        const { current } = ref;
        current.innerHTML += '<ecg-line></ecg-line>';
        ecgLine((bang) => setInterval(() => bang(), 1000));
      }, []);

      return h("div", { ref });
    };

    ReactDOM.render(h(App), document.getElementById('mount-point'));

  })()
</script>
```

If you want to use this component with WebPack or other bundler, you need to place it's source in the global scope (window). This was discussed on StackOverflow [here](https://stackoverflow.com/questions/48998102/webpack-how-to-load-non-module-scripts-into-global-scope-window).  Also you can code with React without any bundler, check the source code [another tool here](https://github.com/tripolskypetr/material-ui-umd/blob/master/packages/form-generator-app/src/main.tsx)(english documentation will be published soon).

![image](https://user-images.githubusercontent.com/19227776/94296744-009c1000-ff6c-11ea-813d-4751b196c808.png)

If this tool helps you, a your ⭐    will be appreciated)

**Comment by tripolskypetr** [comment]
```
ecgLine((bang) => {
  const handler = async () => {
    const data = await fetch('http://127.0.0.1/heart/wasBeat');
    const json = await data.json();
    if (json.wasBeat) {
      bang()
    }
    setTimeout(handler, 100);
  };
  handler();
});
```
