### ISSUE TITLE
What do I need to do if I want to make real-time data with new data renderings every 10 seconds?

### ISSUE THREAD

**Issue by greenking19** [tripolskypetr/ecg-line-webcomponent#4]
What do I need to do when the 10-second data is rendered and the new data is re-rendered?
Like in this picture👇
![image](https://github.com/tripolskypetr/ecg-line-webcomponent/assets/43332372/1d1e382a-11fa-441b-8f6f-6d045d3b6b74)

**Comment by tripolskypetr** [comment]
```
ecgLine((bang) => { const handler = async () => { const data = await fetch('http://127.0.0.1/heart/wasBeat'); const json = await data.json(); if (json.wasBeat) { bang() } setTimeout(handler, 100); }; handler(); });
```

**Comment by tripolskypetr** [comment]
Duplicate of https://github.com/tripolskypetr/ecg-line-webcomponent/issues/3
